# NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [4]:
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
c = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,8]])
print(c)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 8]]


In [7]:
print(b.ndim)
print(c.ndim)

2
2


In [8]:
print(b.shape)
print(c.shape)

(3, 3)
(3, 4)


In [9]:
d = np.array([
    [[1,2,3],[2,3,4]],
    [[4,5,6],[6,7,8]]
])
print(d)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [6 7 8]]]


In [10]:
print(d.ndim)
print(d.shape)

3
(2, 2, 3)


In [11]:
e = [1,2,3,4,5,6]
f = np.array(e)
print(f)

[1 2 3 4 5 6]


In [12]:
g = np.zeros(5)
print(g)

[0. 0. 0. 0. 0.]


In [13]:
h = np.zeros((5,5))
print(h)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
i = np.ones((5,5))
print(i)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
range(5)
list(range(5))

[0, 1, 2, 3, 4]

In [16]:
j = np.arange(4,25,4)
print(j)

[ 4  8 12 16 20 24]


In [17]:
a_list = list(range(15))

## np.append

In [18]:
a_list.append(list(range(7)))

In [19]:
print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, [0, 1, 2, 3, 4, 5, 6]]


In [20]:
a_list.append(90)
print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, [0, 1, 2, 3, 4, 5, 6], 90]


In [21]:
# ketika append list/array, shape-nya harus sama

In [22]:
k = np.append([[1,2,3],[4,5,6]],
              [[7,8,9],[7,8,9]], axis=1)
print(k)

[[1 2 3 7 8 9]
 [4 5 6 7 8 9]]


In [23]:
m = np.array([[1,2,3],[4,5,6]])
n = np.array([3,4,5])

In [24]:
p = np.append(m,n)
print(p)

[1 2 3 4 5 6 3 4 5]


In [29]:
p = np.append(m,n,axis=1)
print(p)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [30]:
np.append()

TypeError: append() missing 2 required positional arguments: 'arr' and 'values'

## np.delete

In [31]:
print(a)
np.delete(a,1)

[1 2 3 4 5 6]


array([1, 3, 4, 5, 6])

In [34]:
print(b)
np.delete(b,1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 3, 4, 5, 6, 7, 8, 9])

## np.sort

In [35]:
np.sort(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
q = np.array([2,4,6,4,3,5,8,7,6,5,6])
np.sort(q)

array([2, 3, 4, 4, 5, 5, 6, 6, 6, 7, 8])

In [37]:
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


In [38]:
r = np.array([
    [2,3,4,5],
    [5,6,7,8],
    [8,7,6,5]
])
print(r)

[[2 3 4 5]
 [5 6 7 8]
 [8 7 6 5]]


In [39]:
s = r.reshape(4,3)
print(s)

[[2 3 4]
 [5 5 6]
 [7 8 8]
 [7 6 5]]


In [40]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
t = np.arange(5)
print(t)
t[np.newaxis]

[0 1 2 3 4]


array([[0, 1, 2, 3, 4]])

In [42]:
t[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [43]:
u = np.arange(6)
print(u)

[0 1 2 3 4 5]


In [44]:
u[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
v = u.reshape(2,3)
print(v)

[[0 1 2]
 [3 4 5]]


In [45]:
np.expand_dims(v,axis=1).shape

(2, 1, 3)

## indexing

In [46]:
w = v[0]
print(w)

[0 1 2]


In [47]:
x = v[1]
print(x)

[3 4 5]


In [48]:
x = np.arange(7)
print(x)


[0 1 2 3 4 5 6]


In [49]:
a > 2

array([False, False,  True,  True,  True,  True])

In [50]:
v > 2

array([[False, False, False],
       [ True,  True,  True]])

In [51]:
x[np.array([True,False,True,False,True,False,False])]

array([0, 2, 4])

In [52]:
x[x<5]

array([0, 1, 2, 3, 4])

In [53]:
x[x>4]

array([5, 6])

In [54]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12])

In [55]:
b % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [56]:
x[x %  2 == 0]
x[x %  2 == 1]

array([1, 3, 5])

In [57]:
a_1 = np.array([
    [1,2,3],
    [3,4,5]
    ])

a_2 = np.array([
    [3,4,5],
    [6,7,8]
])

In [58]:
np.append(a_1,a_2)

array([1, 2, 3, 3, 4, 5, 3, 4, 5, 6, 7, 8])

In [59]:
np.append(a_1,a_2,axis=1)

array([[1, 2, 3, 3, 4, 5],
       [3, 4, 5, 6, 7, 8]])

In [60]:
np.append(a_1,a_2,axis=0)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.vstack(a_1,a_2)

TypeError: vstack() takes 1 positional argument but 2 were given

In [63]:
np.hstack(a_1,a_2)

TypeError: hstack() takes 1 positional argument but 2 were given

In [64]:
a_3 = np.append(a_1,a_2,axis=0)
print(a_3)

[[1 2 3]
 [3 4 5]
 [3 4 5]
 [6 7 8]]


In [65]:
np.split(a_3,4)

[array([[1, 2, 3]]),
 array([[3, 4, 5]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]])]

In [66]:
b1, b2, b3, b4 = np.vsplit(a_3,4)

In [67]:
print(b1)
print(b2)
print(b3)
print(b4)

[[1 2 3]]
[[3 4 5]]
[[3 4 5]]
[[6 7 8]]


In [68]:
np.hstack(b1,b2,b3,b4)

TypeError: hstack() takes 1 positional argument but 4 were given

In [69]:
np.vstack(b1,b2,b3,b4)

TypeError: vstack() takes 1 positional argument but 4 were given

In [70]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
c1 = b.view()
cc = c1[c1 & 2 == 0]
print(cc)
print(b)

[1 4 5 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
c2 = b.copy()
print (c2)
cd = c1[c1 & 2 == 0]
print(cd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 5 8 9]


In [ ]:
# perkalian array akan per element array

In [73]:
print(v)
print(b)
np.dot(v,b)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[18, 21, 24],
       [54, 66, 78]])

In [74]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [75]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [76]:
b.sum(axis=0)

array([3, 3])

In [77]:
b.sum(axis=1)

array([2, 4])

In [78]:
data = np.array([1, 2])
data

array([1, 2])

In [79]:
ones = np.ones(2)
ones

array([1., 1.])

In [80]:
data + ones

array([2., 3.])

In [81]:
data * data

array([1, 4])

In [82]:
data / data

array([1., 1.])

# Broadcasting

In [83]:
data * 2

array([2, 4])

In [85]:
data.max()

2

In [86]:
data.min()

1

In [87]:
data.sum()

3

In [88]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [89]:
A.sum()

4.8595784

In [90]:
A.min()

0.05093587

In [91]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [92]:
A.max()

0.82485143

In [93]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [94]:
A.std()

0.21392120766089617

# Membuat matrix

In [95]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [96]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
np.random.random((3,2))

array([[0.46645705, 0.19230099],
       [0.49469184, 0.95719778],
       [0.72102859, 0.29082891]])

# Aritmatika Matrix

In [98]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [99]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [100]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [101]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [102]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [103]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [104]:
a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [105]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [107]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)


[[1 2]
 [3 4]
 [5 6]]


In [108]:
print(data[0])

[1 2]


In [109]:
print(data[1])

[3 4]


In [110]:
print(data[2])

[5 6]


In [111]:
print(data[0,1])

2


In [112]:
print(data[1:3])

[[3 4]
 [5 6]]


In [113]:
print(data[0:2,1])

[2 4]


# Matrix Aggregation

In [114]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [115]:
print(data.max())

6


In [116]:
print(data.min())

1


In [117]:
print(data.sum())

21


In [118]:
print(data.max(axis=0))

[5 6]


In [119]:
print(data.max(axis=1))

[2 4 6]


# Transposing and Reshaping

In [120]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [121]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [122]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T

In [123]:
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [124]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
arr = np.arange(6).reshape((2, 3))

In [127]:
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [128]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

In [129]:
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [130]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [131]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [132]:
print(np.random.random((4,3,2)))

[[[0.97904422 0.74819855]
  [0.86986907 0.7025141 ]
  [0.85086524 0.33904705]]

 [[0.92526931 0.65899954]
  [0.44053319 0.83862724]
  [0.49679455 0.26004686]]

 [[0.67030629 0.73207509]
  [0.85450027 0.00606462]
  [0.81037205 0.44187522]]

 [[0.72582246 0.66278801]
  [0.20337131 0.14628021]
  [0.46019984 0.20407752]]]


# Flatten N-Dimensional Array

In [133]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [135]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'observed' is not defined